// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple_proto.proto

package protobuf;

public final class SimpleProto {
  private SimpleProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PingEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.PingEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required uint32 opt = 2;</code>
     */
    boolean hasOpt();
    /**
     * <code>required uint32 opt = 2;</code>
     */
    int getOpt();

    /**
     * <code>required string str = 3;</code>
     */
    boolean hasStr();
    /**
     * <code>required string str = 3;</code>
     */
    java.lang.String getStr();
    /**
     * <code>required string str = 3;</code>
     */
    com.google.protobuf.ByteString
        getStrBytes();

    /**
     * <code>required .protobuf.PingEntity.PingType type = 4;</code>
     */
    boolean hasType();
    /**
     * <code>required .protobuf.PingEntity.PingType type = 4;</code>
     */
    protobuf.SimpleProto.PingEntity.PingType getType();

    /**
     * <code>repeated string phone = 5;</code>
     */
    java.util.List<java.lang.String>
        getPhoneList();
    /**
     * <code>repeated string phone = 5;</code>
     */
    int getPhoneCount();
    /**
     * <code>repeated string phone = 5;</code>
     */
    java.lang.String getPhone(int index);
    /**
     * <code>repeated string phone = 5;</code>
     */
    com.google.protobuf.ByteString
        getPhoneBytes(int index);
  }
  /**
   * Protobuf type {@code protobuf.PingEntity}
   */
  public  static final class PingEntity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.PingEntity)
      PingEntityOrBuilder {
    // Use PingEntity.newBuilder() to construct.
    private PingEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PingEntity() {
      id_ = 0;
      opt_ = 0;
      str_ = "";
      type_ = 1;
      phone_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PingEntity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              opt_ = input.readUInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              str_ = bs;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              protobuf.SimpleProto.PingEntity.PingType value = protobuf.SimpleProto.PingEntity.PingType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                type_ = rawValue;
              }
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                phone_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              phone_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          phone_ = phone_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.SimpleProto.internal_static_protobuf_PingEntity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.SimpleProto.internal_static_protobuf_PingEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.SimpleProto.PingEntity.class, protobuf.SimpleProto.PingEntity.Builder.class);
    }

    /**
     * Protobuf enum {@code protobuf.PingEntity.PingType}
     */
    public enum PingType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TYPE1 = 1;</code>
       */
      TYPE1(1),
      /**
       * <code>TYPE2 = 2;</code>
       */
      TYPE2(2),
      /**
       * <code>TYPE3 = 3;</code>
       */
      TYPE3(3),
      ;

      /**
       * <code>TYPE1 = 1;</code>
       */
      public static final int TYPE1_VALUE = 1;
      /**
       * <code>TYPE2 = 2;</code>
       */
      public static final int TYPE2_VALUE = 2;
      /**
       * <code>TYPE3 = 3;</code>
       */
      public static final int TYPE3_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PingType valueOf(int value) {
        return forNumber(value);
      }

      public static PingType forNumber(int value) {
        switch (value) {
          case 1: return TYPE1;
          case 2: return TYPE2;
          case 3: return TYPE3;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PingType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PingType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PingType>() {
              public PingType findValueByNumber(int number) {
                return PingType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protobuf.SimpleProto.PingEntity.getDescriptor().getEnumTypes().get(0);
      }

      private static final PingType[] VALUES = values();

      public static PingType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PingType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuf.PingEntity.PingType)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int OPT_FIELD_NUMBER = 2;
    private int opt_;
    /**
     * <code>required uint32 opt = 2;</code>
     */
    public boolean hasOpt() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 opt = 2;</code>
     */
    public int getOpt() {
      return opt_;
    }

    public static final int STR_FIELD_NUMBER = 3;
    private volatile java.lang.Object str_;
    /**
     * <code>required string str = 3;</code>
     */
    public boolean hasStr() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string str = 3;</code>
     */
    public java.lang.String getStr() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          str_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string str = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStrBytes() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>required .protobuf.PingEntity.PingType type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .protobuf.PingEntity.PingType type = 4;</code>
     */
    public protobuf.SimpleProto.PingEntity.PingType getType() {
      protobuf.SimpleProto.PingEntity.PingType result = protobuf.SimpleProto.PingEntity.PingType.valueOf(type_);
      return result == null ? protobuf.SimpleProto.PingEntity.PingType.TYPE1 : result;
    }

    public static final int PHONE_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList phone_;
    /**
     * <code>repeated string phone = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPhoneList() {
      return phone_;
    }
    /**
     * <code>repeated string phone = 5;</code>
     */
    public int getPhoneCount() {
      return phone_.size();
    }
    /**
     * <code>repeated string phone = 5;</code>
     */
    public java.lang.String getPhone(int index) {
      return phone_.get(index);
    }
    /**
     * <code>repeated string phone = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPhoneBytes(int index) {
      return phone_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOpt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, opt_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, str_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, type_);
      }
      for (int i = 0; i < phone_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, phone_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, opt_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, str_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < phone_.size(); i++) {
          dataSize += computeStringSizeNoTag(phone_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPhoneList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.SimpleProto.PingEntity)) {
        return super.equals(obj);
      }
      protobuf.SimpleProto.PingEntity other = (protobuf.SimpleProto.PingEntity) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasOpt() == other.hasOpt());
      if (hasOpt()) {
        result = result && (getOpt()
            == other.getOpt());
      }
      result = result && (hasStr() == other.hasStr());
      if (hasStr()) {
        result = result && getStr()
            .equals(other.getStr());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && getPhoneList()
          .equals(other.getPhoneList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasOpt()) {
        hash = (37 * hash) + OPT_FIELD_NUMBER;
        hash = (53 * hash) + getOpt();
      }
      if (hasStr()) {
        hash = (37 * hash) + STR_FIELD_NUMBER;
        hash = (53 * hash) + getStr().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (getPhoneCount() > 0) {
        hash = (37 * hash) + PHONE_FIELD_NUMBER;
        hash = (53 * hash) + getPhoneList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.SimpleProto.PingEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.SimpleProto.PingEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.SimpleProto.PingEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.SimpleProto.PingEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.SimpleProto.PingEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.SimpleProto.PingEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.SimpleProto.PingEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.SimpleProto.PingEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.SimpleProto.PingEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.SimpleProto.PingEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.SimpleProto.PingEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.PingEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.PingEntity)
        protobuf.SimpleProto.PingEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.SimpleProto.internal_static_protobuf_PingEntity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.SimpleProto.internal_static_protobuf_PingEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.SimpleProto.PingEntity.class, protobuf.SimpleProto.PingEntity.Builder.class);
      }

      // Construct using protobuf.SimpleProto.PingEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        opt_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        str_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000008);
        phone_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.SimpleProto.internal_static_protobuf_PingEntity_descriptor;
      }

      public protobuf.SimpleProto.PingEntity getDefaultInstanceForType() {
        return protobuf.SimpleProto.PingEntity.getDefaultInstance();
      }

      public protobuf.SimpleProto.PingEntity build() {
        protobuf.SimpleProto.PingEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.SimpleProto.PingEntity buildPartial() {
        protobuf.SimpleProto.PingEntity result = new protobuf.SimpleProto.PingEntity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.opt_ = opt_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.str_ = str_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          phone_ = phone_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.phone_ = phone_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.SimpleProto.PingEntity) {
          return mergeFrom((protobuf.SimpleProto.PingEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.SimpleProto.PingEntity other) {
        if (other == protobuf.SimpleProto.PingEntity.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasOpt()) {
          setOpt(other.getOpt());
        }
        if (other.hasStr()) {
          bitField0_ |= 0x00000004;
          str_ = other.str_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (!other.phone_.isEmpty()) {
          if (phone_.isEmpty()) {
            phone_ = other.phone_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensurePhoneIsMutable();
            phone_.addAll(other.phone_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasOpt()) {
          return false;
        }
        if (!hasStr()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.SimpleProto.PingEntity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.SimpleProto.PingEntity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int opt_ ;
      /**
       * <code>required uint32 opt = 2;</code>
       */
      public boolean hasOpt() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 opt = 2;</code>
       */
      public int getOpt() {
        return opt_;
      }
      /**
       * <code>required uint32 opt = 2;</code>
       */
      public Builder setOpt(int value) {
        bitField0_ |= 0x00000002;
        opt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 opt = 2;</code>
       */
      public Builder clearOpt() {
        bitField0_ = (bitField0_ & ~0x00000002);
        opt_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object str_ = "";
      /**
       * <code>required string str = 3;</code>
       */
      public boolean hasStr() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string str = 3;</code>
       */
      public java.lang.String getStr() {
        java.lang.Object ref = str_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            str_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string str = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStrBytes() {
        java.lang.Object ref = str_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          str_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string str = 3;</code>
       */
      public Builder setStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        str_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string str = 3;</code>
       */
      public Builder clearStr() {
        bitField0_ = (bitField0_ & ~0x00000004);
        str_ = getDefaultInstance().getStr();
        onChanged();
        return this;
      }
      /**
       * <code>required string str = 3;</code>
       */
      public Builder setStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        str_ = value;
        onChanged();
        return this;
      }

      private int type_ = 1;
      /**
       * <code>required .protobuf.PingEntity.PingType type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .protobuf.PingEntity.PingType type = 4;</code>
       */
      public protobuf.SimpleProto.PingEntity.PingType getType() {
        protobuf.SimpleProto.PingEntity.PingType result = protobuf.SimpleProto.PingEntity.PingType.valueOf(type_);
        return result == null ? protobuf.SimpleProto.PingEntity.PingType.TYPE1 : result;
      }
      /**
       * <code>required .protobuf.PingEntity.PingType type = 4;</code>
       */
      public Builder setType(protobuf.SimpleProto.PingEntity.PingType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .protobuf.PingEntity.PingType type = 4;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 1;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList phone_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePhoneIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          phone_ = new com.google.protobuf.LazyStringArrayList(phone_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string phone = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPhoneList() {
        return phone_.getUnmodifiableView();
      }
      /**
       * <code>repeated string phone = 5;</code>
       */
      public int getPhoneCount() {
        return phone_.size();
      }
      /**
       * <code>repeated string phone = 5;</code>
       */
      public java.lang.String getPhone(int index) {
        return phone_.get(index);
      }
      /**
       * <code>repeated string phone = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes(int index) {
        return phone_.getByteString(index);
      }
      /**
       * <code>repeated string phone = 5;</code>
       */
      public Builder setPhone(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhoneIsMutable();
        phone_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phone = 5;</code>
       */
      public Builder addPhone(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhoneIsMutable();
        phone_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phone = 5;</code>
       */
      public Builder addAllPhone(
          java.lang.Iterable<java.lang.String> values) {
        ensurePhoneIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phone_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phone = 5;</code>
       */
      public Builder clearPhone() {
        phone_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string phone = 5;</code>
       */
      public Builder addPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhoneIsMutable();
        phone_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.PingEntity)
    }

    // @@protoc_insertion_point(class_scope:protobuf.PingEntity)
    private static final protobuf.SimpleProto.PingEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.SimpleProto.PingEntity();
    }

    public static protobuf.SimpleProto.PingEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PingEntity>
        PARSER = new com.google.protobuf.AbstractParser<PingEntity>() {
      public PingEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PingEntity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PingEntity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PingEntity> getParserForType() {
      return PARSER;
    }

    public protobuf.SimpleProto.PingEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PongEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.PongEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required string opt = 2;</code>
     */
    boolean hasOpt();
    /**
     * <code>required string opt = 2;</code>
     */
    java.lang.String getOpt();
    /**
     * <code>required string opt = 2;</code>
     */
    com.google.protobuf.ByteString
        getOptBytes();

    /**
     * <code>required string str = 3;</code>
     */
    boolean hasStr();
    /**
     * <code>required string str = 3;</code>
     */
    java.lang.String getStr();
    /**
     * <code>required string str = 3;</code>
     */
    com.google.protobuf.ByteString
        getStrBytes();
  }
  /**
   * Protobuf type {@code protobuf.PongEntity}
   */
  public  static final class PongEntity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.PongEntity)
      PongEntityOrBuilder {
    // Use PongEntity.newBuilder() to construct.
    private PongEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PongEntity() {
      id_ = 0;
      opt_ = "";
      str_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PongEntity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              opt_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              str_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.SimpleProto.internal_static_protobuf_PongEntity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.SimpleProto.internal_static_protobuf_PongEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.SimpleProto.PongEntity.class, protobuf.SimpleProto.PongEntity.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int OPT_FIELD_NUMBER = 2;
    private volatile java.lang.Object opt_;
    /**
     * <code>required string opt = 2;</code>
     */
    public boolean hasOpt() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string opt = 2;</code>
     */
    public java.lang.String getOpt() {
      java.lang.Object ref = opt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          opt_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string opt = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOptBytes() {
      java.lang.Object ref = opt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        opt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STR_FIELD_NUMBER = 3;
    private volatile java.lang.Object str_;
    /**
     * <code>required string str = 3;</code>
     */
    public boolean hasStr() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string str = 3;</code>
     */
    public java.lang.String getStr() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          str_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string str = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStrBytes() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOpt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, opt_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, str_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, opt_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, str_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.SimpleProto.PongEntity)) {
        return super.equals(obj);
      }
      protobuf.SimpleProto.PongEntity other = (protobuf.SimpleProto.PongEntity) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasOpt() == other.hasOpt());
      if (hasOpt()) {
        result = result && getOpt()
            .equals(other.getOpt());
      }
      result = result && (hasStr() == other.hasStr());
      if (hasStr()) {
        result = result && getStr()
            .equals(other.getStr());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasOpt()) {
        hash = (37 * hash) + OPT_FIELD_NUMBER;
        hash = (53 * hash) + getOpt().hashCode();
      }
      if (hasStr()) {
        hash = (37 * hash) + STR_FIELD_NUMBER;
        hash = (53 * hash) + getStr().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.SimpleProto.PongEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.SimpleProto.PongEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.SimpleProto.PongEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.SimpleProto.PongEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.SimpleProto.PongEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.SimpleProto.PongEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.SimpleProto.PongEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.SimpleProto.PongEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.SimpleProto.PongEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.SimpleProto.PongEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.SimpleProto.PongEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.PongEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.PongEntity)
        protobuf.SimpleProto.PongEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.SimpleProto.internal_static_protobuf_PongEntity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.SimpleProto.internal_static_protobuf_PongEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.SimpleProto.PongEntity.class, protobuf.SimpleProto.PongEntity.Builder.class);
      }

      // Construct using protobuf.SimpleProto.PongEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        opt_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        str_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.SimpleProto.internal_static_protobuf_PongEntity_descriptor;
      }

      public protobuf.SimpleProto.PongEntity getDefaultInstanceForType() {
        return protobuf.SimpleProto.PongEntity.getDefaultInstance();
      }

      public protobuf.SimpleProto.PongEntity build() {
        protobuf.SimpleProto.PongEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.SimpleProto.PongEntity buildPartial() {
        protobuf.SimpleProto.PongEntity result = new protobuf.SimpleProto.PongEntity(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.opt_ = opt_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.str_ = str_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.SimpleProto.PongEntity) {
          return mergeFrom((protobuf.SimpleProto.PongEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.SimpleProto.PongEntity other) {
        if (other == protobuf.SimpleProto.PongEntity.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasOpt()) {
          bitField0_ |= 0x00000002;
          opt_ = other.opt_;
          onChanged();
        }
        if (other.hasStr()) {
          bitField0_ |= 0x00000004;
          str_ = other.str_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasOpt()) {
          return false;
        }
        if (!hasStr()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.SimpleProto.PongEntity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.SimpleProto.PongEntity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object opt_ = "";
      /**
       * <code>required string opt = 2;</code>
       */
      public boolean hasOpt() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string opt = 2;</code>
       */
      public java.lang.String getOpt() {
        java.lang.Object ref = opt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            opt_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string opt = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOptBytes() {
        java.lang.Object ref = opt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          opt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string opt = 2;</code>
       */
      public Builder setOpt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        opt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string opt = 2;</code>
       */
      public Builder clearOpt() {
        bitField0_ = (bitField0_ & ~0x00000002);
        opt_ = getDefaultInstance().getOpt();
        onChanged();
        return this;
      }
      /**
       * <code>required string opt = 2;</code>
       */
      public Builder setOptBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        opt_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object str_ = "";
      /**
       * <code>required string str = 3;</code>
       */
      public boolean hasStr() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string str = 3;</code>
       */
      public java.lang.String getStr() {
        java.lang.Object ref = str_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            str_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string str = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStrBytes() {
        java.lang.Object ref = str_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          str_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string str = 3;</code>
       */
      public Builder setStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        str_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string str = 3;</code>
       */
      public Builder clearStr() {
        bitField0_ = (bitField0_ & ~0x00000004);
        str_ = getDefaultInstance().getStr();
        onChanged();
        return this;
      }
      /**
       * <code>required string str = 3;</code>
       */
      public Builder setStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        str_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.PongEntity)
    }

    // @@protoc_insertion_point(class_scope:protobuf.PongEntity)
    private static final protobuf.SimpleProto.PongEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.SimpleProto.PongEntity();
    }

    public static protobuf.SimpleProto.PongEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PongEntity>
        PARSER = new com.google.protobuf.AbstractParser<PongEntity>() {
      public PongEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PongEntity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PongEntity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PongEntity> getParserForType() {
      return PARSER;
    }

    public protobuf.SimpleProto.PongEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code protobuf.Ping2PongService}
   */
  public static abstract class Ping2PongService
      implements com.google.protobuf.Service {
    protected Ping2PongService() {}

    public interface Interface {
      /**
       * <code>rpc get(.protobuf.PingEntity) returns (.protobuf.PongEntity);</code>
       */
      public abstract void get(
          com.google.protobuf.RpcController controller,
          protobuf.SimpleProto.PingEntity request,
          com.google.protobuf.RpcCallback<protobuf.SimpleProto.PongEntity> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new Ping2PongService() {
        @java.lang.Override
        public  void get(
            com.google.protobuf.RpcController controller,
            protobuf.SimpleProto.PingEntity request,
            com.google.protobuf.RpcCallback<protobuf.SimpleProto.PongEntity> done) {
          impl.get(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.get(controller, (protobuf.SimpleProto.PingEntity)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return protobuf.SimpleProto.PingEntity.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return protobuf.SimpleProto.PongEntity.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc get(.protobuf.PingEntity) returns (.protobuf.PongEntity);</code>
     */
    public abstract void get(
        com.google.protobuf.RpcController controller,
        protobuf.SimpleProto.PingEntity request,
        com.google.protobuf.RpcCallback<protobuf.SimpleProto.PongEntity> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return protobuf.SimpleProto.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.get(controller, (protobuf.SimpleProto.PingEntity)request,
            com.google.protobuf.RpcUtil.<protobuf.SimpleProto.PongEntity>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return protobuf.SimpleProto.PingEntity.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return protobuf.SimpleProto.PongEntity.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends protobuf.SimpleProto.Ping2PongService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void get(
          com.google.protobuf.RpcController controller,
          protobuf.SimpleProto.PingEntity request,
          com.google.protobuf.RpcCallback<protobuf.SimpleProto.PongEntity> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          protobuf.SimpleProto.PongEntity.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            protobuf.SimpleProto.PongEntity.class,
            protobuf.SimpleProto.PongEntity.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public protobuf.SimpleProto.PongEntity get(
          com.google.protobuf.RpcController controller,
          protobuf.SimpleProto.PingEntity request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public protobuf.SimpleProto.PongEntity get(
          com.google.protobuf.RpcController controller,
          protobuf.SimpleProto.PingEntity request)
          throws com.google.protobuf.ServiceException {
        return (protobuf.SimpleProto.PongEntity) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          protobuf.SimpleProto.PongEntity.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:protobuf.Ping2PongService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_PingEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_PingEntity_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_PongEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_PongEntity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022simple_proto.proto\022\010protobuf\"\233\001\n\nPingE" +
      "ntity\022\n\n\002id\030\001 \002(\r\022\013\n\003opt\030\002 \002(\r\022\013\n\003str\030\003 " +
      "\002(\t\022+\n\004type\030\004 \002(\0162\035.protobuf.PingEntity." +
      "PingType\022\r\n\005phone\030\005 \003(\t\"+\n\010PingType\022\t\n\005T" +
      "YPE1\020\001\022\t\n\005TYPE2\020\002\022\t\n\005TYPE3\020\003\"2\n\nPongEnti" +
      "ty\022\n\n\002id\030\001 \002(\r\022\013\n\003opt\030\002 \002(\t\022\013\n\003str\030\003 \002(\t" +
      "2E\n\020Ping2PongService\0221\n\003get\022\024.protobuf.P" +
      "ingEntity\032\024.protobuf.PongEntityB\003\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_PingEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_PingEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_PingEntity_descriptor,
        new java.lang.String[] { "Id", "Opt", "Str", "Type", "Phone", });
    internal_static_protobuf_PongEntity_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_PongEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_PongEntity_descriptor,
        new java.lang.String[] { "Id", "Opt", "Str", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
